runtime: nodejs22
service: client

build_env_variables:
  NEXT_PUBLIC_BACKEND_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app"
  NEXT_PUBLIC_API_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app/api"
  NEXT_PUBLIC_APP_API_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app/api"
  NEXT_PUBLIC_SITE_URL: "https://healthyonegram.com"
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyByup2bUIVoMS9nad6TkfyPNKPqWgAJKWA"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "studio-8452116634-cdb59.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "studio-8452116634-cdb59"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "studio-8452116634-cdb59.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "381544785154"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:381544785154:web:a3d4807189bad3c8774e1b"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-BWVFHX07P7"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "BL22YBdvb5TkydQ5LsnePfUgLQsf61THj-Ja72oli6FMb1U7lh-GYJJ__gjIvf8nZjAJ7s8aBQzq1ahFBxpSTi8"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyAs_C6O3bS4fi1lBBRJG2oPVVtM7fkALS8"

env_variables:
  NEXT_PUBLIC_BACKEND_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app"
  NEXT_PUBLIC_API_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app/api"
  NEXT_PUBLIC_APP_API_URL: "https://healthyonegram-api-v2-xb7znoco6a-uc.a.run.app/api"
  NEXT_PUBLIC_SITE_URL: "https://healthyonegram.com"
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyByup2bUIVoMS9nad6TkfyPNKPqWgAJKWA"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "studio-8452116634-cdb59.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "studio-8452116634-cdb59"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "studio-8452116634-cdb59.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "381544785154"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:381544785154:web:a3d4807189bad3c8774e1b"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-BWVFHX07P7"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "BL22YBdvb5TkydQ5LsnePfUgLQsf61THj-Ja72oli6FMb1U7lh-GYJJ__gjIvf8nZjAJ7s8aBQzq1ahFBxpSTi8"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyAs_C6O3bS4fi1lBBRJG2oPVVtM7fkALS8"


instance_class: F1

automatic_scaling:
  min_instances: 0
  min_idle_instances: 0
  max_idle_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.9
